(function(){"use strict";const cfg=window.NX_CONFIG,db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey);let owner=null,orders=[],users=[],products=[],activeView='dashboard';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v||0));const fmt=v=>v?new Date(v).toLocaleString([],{dateStyle:'medium',timeStyle:'short'}):'—';
function toast(m,e=false){const x=$('#toast');x.textContent=m;x.style.background=e?'#b4232b':'#171a21';x.classList.remove('hidden');clearTimeout(toast.t);toast.t=setTimeout(()=>x.classList.add('hidden'),3200)}function label(s){return({awaiting_payment:'Payment pending',payment_confirmed:'Payment confirmed',processing:'Processing',delivered:'Delivered',cancelled:'Cancelled'})[s]||s||'Pending'}
function showView(id){activeView=id;$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));renderAll();scrollTo({top:0,behavior:'smooth'})}
async function verifyOwner(user){const {data,error}=await db.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();return !error&&!!data}
async function enter(user){if(!await verifyOwner(user)){await db.auth.signOut();showLogin('This account is not authorized for the owner console.');return}owner=user;$('#loginView').classList.add('hidden');$('#adminApp').classList.remove('hidden');$('#ownerEmail').textContent=user.email||'Owner';$('#ownerAvatar').textContent=(user.email||'N').charAt(0).toUpperCase();await loadAll()}
function showLogin(message=''){$('#loginView').classList.remove('hidden');$('#adminApp').classList.add('hidden');if(message){$('#loginMessage').textContent=message;$('#loginMessage').classList.remove('hidden')}}
async function loadAll(){const [o,u,p]=await Promise.all([db.from('orders').select('id,order_number,customer_id,customer_email,amount_usd,status,download_url,transaction_hash,payment_submitted_at,created_at,updated_at,products(name)').order('created_at',{ascending:false}),db.from('profiles').select('id,full_name,email,business_email,country,role,status,created_at').order('created_at',{ascending:false}),db.from('products').select('id,name,category,price_usd,quantity,unit_label,active,created_at').order('name')]);const err=o.error||u.error||p.error;if(err)return toast('Admin data could not load: '+err.message,true);orders=o.data||[];users=u.data||[];products=p.data||[];renderAll()}
function renderAll(){const q=$('#adminSearch').value.trim().toLowerCase();$('#mUsers').textContent=users.filter(u=>u.status!=='deleted').length;$('#mOrders').textContent=orders.length;$('#mPending').textContent=orders.filter(o=>['awaiting_payment','payment_confirmed','processing'].includes(o.status)).length;$('#mRevenue').textContent=money(orders.filter(o=>!['cancelled'].includes(o.status)).reduce((s,o)=>s+Number(o.amount_usd),0));renderOrders('#recentOrders',orders.slice(0,6));renderOrders('#ordersTable',orders.filter(o=>!q||JSON.stringify(o).toLowerCase().includes(q)));renderUsers(users.filter(u=>!q||JSON.stringify(u).toLowerCase().includes(q)));renderProducts(products.filter(p=>!q||JSON.stringify(p).toLowerCase().includes(q)))}
function renderOrders(target,list){const box=$(target);if(!list.length){box.innerHTML='<div class="empty">No orders found.</div>';return}box.innerHTML=`<div class="table-scroll"><table class="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Dataset</th><th>Amount</th><th>Status</th><th>TxID</th><th>Action</th><th>Created</th></tr></thead><tbody>${list.map(o=>`<tr><td><b>${esc(o.order_number)}</b></td><td>${esc(o.customer_email)}</td><td>${esc(o.products?.name||'Dataset')}</td><td>${money(o.amount_usd)}</td><td><span class="status ${esc(o.status)}">${esc(label(o.status))}</span></td><td title="${esc(o.transaction_hash||'')}">${o.transaction_hash?esc(o.transaction_hash.slice(0,10))+'…':'—'}</td><td>${orderActions(o)}</td><td>${fmt(o.created_at)}</td></tr>`).join('')}</tbody></table></div>`;box.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>setOrderStatus(b.dataset.id,b.dataset.status));box.querySelectorAll('[data-deliver]').forEach(b=>b.onclick=()=>deliveryModal(b.dataset.deliver));box.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>setOrderStatus(b.dataset.cancel,'cancelled'))}
function orderActions(o){if(o.status==='awaiting_payment')return `<div class="row-actions"><button class="primary small-btn" data-status="payment_confirmed" data-id="${o.id}">Confirm</button><button class="danger small-btn" data-cancel="${o.id}">Cancel</button></div>`;if(o.status==='payment_confirmed')return `<button class="primary small-btn" data-status="processing" data-id="${o.id}">Start processing</button>`;if(o.status==='processing')return `<button class="primary small-btn" data-deliver="${o.id}">Deliver file</button>`;if(o.status==='delivered')return `<button class="secondary small-btn" data-deliver="${o.id}">Edit link</button>`;return '—'}
async function setOrderStatus(id,status,download_url){const patch={status};if(download_url!==undefined)patch.download_url=download_url;const {error}=await db.from('orders').update(patch).eq('id',id);if(error)return toast(error.message,true);toast('Order updated.');await loadAll()}
function modal(html){$('#modalRoot').innerHTML=`<div class="modal-wrap"><div class="modal">${html}</div></div>`;$('.modal-wrap').onclick=e=>{if(e.target===e.currentTarget)closeModal()}}function closeModal(){$('#modalRoot').innerHTML=''}window.closeNXModal=closeModal;
function deliveryModal(id){const o=orders.find(x=>x.id===id);modal(`<div class="modal-head"><h2>Attach secure delivery</h2><button class="close" onclick="closeNXModal()">×</button></div><form id="deliveryForm" class="form-grid"><div class="note">Order <b>${esc(o.order_number)}</b>. Add an HTTPS file link accessible only to the intended customer where possible.</div><label>Download URL</label><input id="deliveryUrl" class="field" type="url" value="${esc(o.download_url||'')}" placeholder="https://..." required><button class="primary" type="submit">Save and mark delivered</button></form>`);$('#deliveryForm').onsubmit=async e=>{e.preventDefault();const url=$('#deliveryUrl').value.trim();if(!/^https:\/\//i.test(url))return toast('Use a valid HTTPS download URL.',true);await setOrderStatus(id,'delivered',url);closeModal()}}
function renderUsers(list){const box=$('#usersTable');if(!list.length){box.innerHTML='<div class="empty">No users found.</div>';return}box.innerHTML=`<div class="table-scroll"><table class="data-table"><thead><tr><th>User</th><th>Role</th><th>Status</th><th>Country</th><th>Joined</th><th>Action</th></tr></thead><tbody>${list.map(u=>`<tr><td><div class="user-cell"><div class="avatar">${esc((u.full_name||u.email||'U').charAt(0).toUpperCase())}</div><div><b>${esc(u.full_name||'Customer')}</b><div class="unit">${esc(u.email||u.business_email||'—')}</div></div></div></td><td><span class="status ${esc(u.role)}">${esc(u.role)}</span></td><td><span class="status ${esc(u.status)}">${esc(u.status)}</span></td><td>${esc(u.country||'—')}</td><td>${fmt(u.created_at)}</td><td>${u.id===owner?.id?'<span class="tag">OWNER</span>':userActions(u)}</td></tr>`).join('')}</tbody></table></div>`;box.querySelectorAll('[data-user-status]').forEach(b=>b.onclick=()=>setUserStatus(b.dataset.id,b.dataset.userStatus))}
function userActions(u){if(u.status==='active')return `<div class="row-actions"><button class="danger small-btn" data-user-status="blocked" data-id="${u.id}">Block</button><button class="secondary small-btn" data-user-status="deleted" data-id="${u.id}">Deactivate</button></div>`;return `<button class="primary small-btn" data-user-status="active" data-id="${u.id}">Restore access</button>`}
async function setUserStatus(id,status){if(!confirm(`${status==='active'?'Restore':'Change'} this user account?`))return;const {error}=await db.rpc('admin_set_user_status',{target_user:id,next_status:status});if(error)return toast(error.message,true);toast('User access updated.');await loadAll()}
function renderProducts(list){const box=$('#productsTable');if(!list.length){box.innerHTML='<div class="empty">No products found.</div>';return}box.innerHTML=`<div class="table-scroll"><table class="data-table"><thead><tr><th>Dataset</th><th>Category</th><th>Price</th><th>Quantity</th><th>Visibility</th><th>Action</th></tr></thead><tbody>${list.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td>${esc(p.category)}</td><td>${money(p.price_usd)}</td><td>${Number(p.quantity).toLocaleString()} ${esc(p.unit_label)}</td><td><span class="status ${p.active?'active':'blocked'}">${p.active?'Active':'Hidden'}</span></td><td><button class="secondary small-btn" data-product="${p.id}">Edit</button></td></tr>`).join('')}</tbody></table></div>`;box.querySelectorAll('[data-product]').forEach(b=>b.onclick=()=>productModal(b.dataset.product))}
function productModal(id){const p=products.find(x=>x.id===id);modal(`<div class="modal-head"><h2>Edit dataset</h2><button class="close" onclick="closeNXModal()">×</button></div><form id="productForm" class="form-grid"><label>Name</label><input class="field" id="pName" value="${esc(p.name)}" required><label>Category</label><input class="field" id="pCategory" value="${esc(p.category)}" required><label>Price (USD)</label><input class="field" id="pPrice" type="number" min="0" step="0.01" value="${Number(p.price_usd)}" required><label>Quantity</label><input class="field" id="pQuantity" type="number" min="1" value="${Number(p.quantity)}" required><label><input id="pActive" type="checkbox" ${p.active?'checked':''}> Visible in marketplace</label><button class="primary" type="submit">Save changes</button></form>`);$('#productForm').onsubmit=async e=>{e.preventDefault();const patch={name:$('#pName').value.trim(),category:$('#pCategory').value.trim(),price_usd:Number($('#pPrice').value),quantity:Number($('#pQuantity').value),active:$('#pActive').checked};const {error}=await db.from('products').update(patch).eq('id',id);if(error)return toast(error.message,true);closeModal();toast('Product updated.');await loadAll()}}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const b=$('#loginButton');b.disabled=true;b.textContent='Signing in…';const {data,error}=await db.auth.signInWithPassword({email:$('#email').value.trim().toLowerCase(),password:$('#password').value});if(error){showLogin(error.message);b.disabled=false;b.textContent='Sign in securely';return}await enter(data.user);b.disabled=false;b.textContent='Sign in securely'};
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-view-jump]').forEach(b=>b.onclick=()=>showView(b.dataset.viewJump));$('#adminSearch').oninput=renderAll;$('#refresh').onclick=loadAll;$('#signOutSide').onclick=async()=>{await db.auth.signOut();location.reload()};db.auth.onAuthStateChange((e,s)=>{if(e==='SIGNED_OUT')showLogin()});
(async()=>{const {data}=await db.auth.getSession();if(data.session)await enter(data.session.user);else showLogin()})();setInterval(()=>{if(owner)loadAll()},20000);
})();
