(function(){"use strict";
const cfg=window.NX_CONFIG,db=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseKey);let user=null,profile=null,products=[],orders=[],category="All",selected=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=v=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(Number(v||0));
const fmt=v=>v?new Date(v).toLocaleString([], {dateStyle:"medium",timeStyle:"short"}):"—";
function toast(message,error=false){const el=$("#toast");el.textContent=message;el.style.background=error?"#b4232b":"#171a21";el.classList.remove("hidden");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.add("hidden"),3200)}
function statusLabel(s){return({awaiting_payment:"Payment pending",payment_confirmed:"Payment confirmed",processing:"Processing",delivered:"Delivered",cancelled:"Cancelled"})[s]||s||"Pending"}
function showView(id){$$('.view').forEach(x=>x.classList.toggle('active',x.id===id));$$('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===id));if(id==='orders')renderOrders();if(id==='downloads')renderDownloads();if(id==='account')renderAccount();scrollTo({top:0,behavior:'smooth'})}
async function loadProducts(){const {data,error}=await db.from('products').select('id,name,category,description,price_usd,quantity,unit_label,icon,active').eq('active',true).order('name');if(error){toast('Catalog could not load: '+error.message,true);return}products=data||[];$('#datasetCount').textContent=products.length+'+';$('#categoryCount').textContent=new Set(products.map(p=>p.category)).size;renderChips();renderProducts()}
function iconFor(p){const map={B2B:'🏢','Real Estate':'⌂',Education:'🎓',Finance:'◫',Insurance:'◆',Technology:'◉','Social Media':'◎','E-commerce':'▣',Communication:'✦','Crypto & Finance':'◇',Telecom:'⌁',Logistics:'▤'};return p.icon||map[p.category]||'◈'}
function renderChips(){const cats=['All',...new Set(products.map(p=>p.category).filter(Boolean))];$('#chips').innerHTML=cats.map(c=>`<button class="chip ${c===category?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{category=b.dataset.cat;renderChips();renderProducts()})}
function renderProducts(){const q=$('#search').value.trim().toLowerCase();const list=products.filter(p=>(category==='All'||p.category===category)&&(!q||[p.name,p.category,p.description].join(' ').toLowerCase().includes(q)));$('#products').innerHTML=list.length?list.map(p=>`<article class="product-card"><div class="product-top"><div class="product-icon">${iconFor(p)}</div><span class="tag">AVAILABLE</span></div><h3>${esc(p.name)}</h3><p>${esc(p.description||'Quality business dataset for professional campaigns.')}</p><div class="product-bottom"><div><span class="price">${money(p.price_usd)}</span><span class="unit">${Number(p.quantity).toLocaleString()} ${esc(p.unit_label)}</span></div><button class="primary small-btn" data-buy="${p.id}">Order</button></div></article>`).join(''):'<div class="empty" style="grid-column:1/-1">No datasets match your search.</div>';$$('[data-buy]').forEach(b=>b.onclick=()=>openCheckout(b.dataset.buy))}
function modal(html){$('#modalRoot').innerHTML=`<div class="modal-wrap"><div class="modal">${html}</div></div>`;$('.modal-wrap').onclick=e=>{if(e.target===e.currentTarget)closeModal()}}
function closeModal(){$('#modalRoot').innerHTML=''}window.closeNXModal=closeModal;
function authModal(mode='login'){modal(`<div class="modal-head"><h2>Welcome to NX</h2><button class="close" onclick="closeNXModal()">×</button></div><div class="auth-tabs"><button class="auth-tab ${mode==='login'?'active':''}" data-auth-tab="login">Sign in</button><button class="auth-tab ${mode==='signup'?'active':''}" data-auth-tab="signup">Create account</button></div><form id="authForm" class="form-grid"><div id="nameField" class="${mode==='login'?'hidden':''}"><label>Full name</label><input class="field" id="authName" autocomplete="name"></div><label>Email</label><input class="field" id="authEmail" type="email" autocomplete="email" required><label>Password</label><input class="field" id="authPassword" type="password" minlength="8" autocomplete="${mode==='login'?'current-password':'new-password'}" required><button class="primary" type="submit">${mode==='login'?'Sign in':'Create account'}</button><button id="forgot" class="secondary ${mode==='signup'?'hidden':''}" type="button">Forgot password?</button><div class="note">Your account protects order history and private download links.</div></form>`);$$('[data-auth-tab]').forEach(b=>b.onclick=()=>authModal(b.dataset.authTab));$('#authForm').onsubmit=e=>handleAuth(e,mode);$('#forgot').onclick=forgotPassword}
async function handleAuth(e,mode){e.preventDefault();const email=$('#authEmail').value.trim().toLowerCase(),password=$('#authPassword').value,btn=$('#authForm .primary');btn.disabled=true;btn.textContent='Please wait…';let result;if(mode==='signup'){const name=$('#authName').value.trim();if(!name){toast('Enter your full name.',true);btn.disabled=false;return}result=await db.auth.signUp({email,password,options:{data:{name}}})}else result=await db.auth.signInWithPassword({email,password});if(result.error){toast(result.error.message,true);btn.disabled=false;btn.textContent=mode==='login'?'Sign in':'Create account';return}closeModal();toast(mode==='signup'&&!result.data.session?'Account created. Check your email to verify.':'Signed in successfully.');if(result.data.session)await syncUser(result.data.session.user)}
async function forgotPassword(){const email=$('#authEmail').value.trim();if(!email){toast('Enter your email first.',true);return}const {error}=await db.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});toast(error?error.message:'Password reset email sent.',!!error)}
async function syncUser(next){user=next;profile=null;if(user){const {data}=await db.from('profiles').select('id,full_name,email,business_email,country,role,status').eq('id',user.id).maybeSingle();profile=data;await loadOrders()}else{orders=[]}renderHeader();renderAccount();renderOrders();renderDownloads()}
function renderHeader(){const logged=!!user;$('#accountButton').classList.toggle('hidden',logged);$('#avatar').classList.toggle('hidden',!logged);if(logged)$('#avatar').textContent=(profile?.full_name||user.email||'N').charAt(0).toUpperCase()}
async function loadOrders(){if(!user){orders=[];return}const {data,error}=await db.from('orders').select('id,order_number,product_id,customer_email,amount_usd,status,download_url,transaction_hash,payment_submitted_at,created_at,updated_at,products(name)').order('created_at',{ascending:false});if(error){toast('Orders could not load: '+error.message,true);orders=[]}else orders=data||[]}
function renderOrders(){const box=$('#ordersBox');if(!user){box.innerHTML='<div class="empty"><p>Sign in to see your secure order history.</p><button class="primary" id="orderSignIn">Sign in</button></div>';$('#orderSignIn').onclick=()=>authModal();return}if(!orders.length){box.innerHTML='<div class="empty">No orders yet. Browse the marketplace to get started.</div>';return}box.innerHTML=`<div class="table-scroll"><table class="data-table"><thead><tr><th>Order</th><th>Dataset</th><th>Amount</th><th>Status</th><th>Submitted</th></tr></thead><tbody>${orders.map(o=>`<tr><td><b>${esc(o.order_number)}</b></td><td>${esc(o.products?.name||'Dataset')}</td><td>${money(o.amount_usd)}</td><td><span class="status ${esc(o.status)}">${esc(statusLabel(o.status))}</span></td><td>${fmt(o.created_at)}</td></tr>`).join('')}</tbody></table></div>`}
function renderDownloads(){const box=$('#downloadsBox');if(!user){box.innerHTML='<div class="empty">Sign in to access your delivered files.</div>';return}const files=orders.filter(o=>o.status==='delivered'&&/^https?:\/\//i.test(o.download_url||''));box.innerHTML=files.length?files.map(o=>`<div class="product-card" style="min-height:0;margin-bottom:9px"><div class="product-bottom" style="padding:0"><div><b>${esc(o.products?.name||'Lead dataset')}</b><span class="unit">${esc(o.order_number)} · Delivered</span></div><a class="primary small-btn" href="${esc(o.download_url)}" target="_blank" rel="noopener noreferrer">Download</a></div></div>`).join(''):'<div class="empty">No delivered files yet.</div>'}
function renderAccount(){const box=$('#accountPanel');if(!user){box.innerHTML='<div class="empty"><p>Create an account to place orders and receive files.</p><button class="primary" id="accountSignIn">Sign in / Create account</button></div>';$('#accountSignIn').onclick=()=>authModal();return}box.innerHTML=`<div class="user-cell" style="margin-bottom:18px"><div class="avatar">${esc((profile?.full_name||user.email).charAt(0).toUpperCase())}</div><div><b>${esc(profile?.full_name||'NX Customer')}</b><div class="unit">${esc(user.email)}</div></div></div><form id="profileForm" class="form-grid"><label>Full name</label><input class="field" id="profileName" value="${esc(profile?.full_name||'')}"><label>Business email</label><input class="field" id="profileBusiness" type="email" value="${esc(profile?.business_email||user.email||'')}"><label>Country</label><input class="field" id="profileCountry" value="${esc(profile?.country||'')}"><button class="primary" type="submit">Save profile</button><button class="secondary" type="button" id="signOut">Sign out</button></form>`;$('#profileForm').onsubmit=saveProfile;$('#signOut').onclick=async()=>{await db.auth.signOut();toast('Signed out.')};}
async function saveProfile(e){e.preventDefault();const updates={full_name:$('#profileName').value.trim(),business_email:$('#profileBusiness').value.trim(),country:$('#profileCountry').value.trim()};const {error}=await db.from('profiles').update(updates).eq('id',user.id);if(error)return toast(error.message,true);profile={...profile,...updates};renderHeader();toast('Profile updated.')}
function openCheckout(id){selected=products.find(p=>p.id===id);if(!selected)return;if(!user){toast('Sign in before placing an order.');authModal();return}if(profile?.status!=='active'){toast('Your account is not active. Contact support.',true);return}modal(`<div class="modal-head"><div><span class="eyebrow" style="color:#087cff">Secure checkout</span><h2>${esc(selected.name)}</h2></div><button class="close" onclick="closeNXModal()">×</button></div><div class="panel" style="margin-bottom:12px"><div class="product-bottom" style="padding:0"><div><span class="unit">Order total</span><span class="price">${money(selected.price_usd)}</span></div><span class="tag">${Number(selected.quantity).toLocaleString()} ${esc(selected.unit_label)}</span></div></div><img class="qr" alt="TRC20 payment QR" src="https://api.qrserver.com/v1/create-qr-code/?size=220x220&margin=8&data=${encodeURIComponent(cfg.walletAddress)}"><div class="note">Send exactly <b>${money(selected.price_usd)} USDT</b> on the <b>${esc(cfg.paymentNetwork)}</b> network only.</div><div class="wallet" id="walletText">${esc(cfg.walletAddress)}</div><form id="checkoutForm" class="form-grid" style="margin-top:12px"><button class="secondary" type="button" id="copyWallet">Copy wallet address</button><label>Transaction hash / TxID</label><input class="field" id="txid" minlength="16" placeholder="Paste the full transaction hash" required><button class="primary" type="submit">Submit payment for review</button></form>`);$('#copyWallet').onclick=async()=>{await navigator.clipboard.writeText(cfg.walletAddress);toast('Wallet address copied.')};$('#checkoutForm').onsubmit=submitOrder}
async function submitOrder(e){e.preventDefault();const tx=$('#txid').value.trim(),btn=$('#checkoutForm .primary');if(tx.length<16)return toast('Enter a valid full transaction hash.',true);btn.disabled=true;btn.textContent='Creating order…';const payload={customer_id:user.id,product_id:selected.id,transaction_hash:tx,payment_submitted_at:new Date().toISOString()};const {error}=await db.from('orders').insert(payload);if(error){btn.disabled=false;btn.textContent='Submit payment for review';return toast(error.code==='23505'?'This transaction hash was already submitted.':error.message,true)}await loadOrders();closeModal();showView('orders');toast('Order submitted. Payment verification is pending.')}
$$('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-view-jump]').forEach(b=>b.onclick=()=>showView(b.dataset.viewJump));$('#accountButton').onclick=()=>authModal();$('#avatar').onclick=()=>showView('account');$('#search').oninput=renderProducts;$('#browseButton').onclick=()=>$('#catalog').scrollIntoView({behavior:'smooth'});
db.auth.onAuthStateChange((event,session)=>{if(event!=='INITIAL_SESSION')setTimeout(()=>syncUser(session?.user||null),0)});
(async()=>{await loadProducts();const {data}=await db.auth.getSession();await syncUser(data.session?.user||null);setInterval(async()=>{if(user){await loadOrders();if($('#orders').classList.contains('active'))renderOrders();if($('#downloads').classList.contains('active'))renderDownloads()}},15000)})();
})();
